import type { NextPage, NextPageContext } from "next";
import Head from "next/head";
import { useAppSelector } from "../../redux/hooks/hooks";
import styles from "./me.module.css";

const Home: NextPage = () => {
  const user = useAppSelector((state) => state.user);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <h3>{user.name}</h3>
        <hr></hr>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export async function getStaticProps(context: NextPageContext) {
  return {
    props: {
      protected: true,
    },
  };
}

export default Home;
