/* eslint-disable @next/next/no-img-element */
import type { NextPage, NextPageContext } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "./search.module.css";
import Axios from "axios";
import { PostInterface } from "../../interfaces/PostInterface";
import { Alert } from "react-bootstrap";
import PostCard from "../../components/posts/postCard/postCard";
import { useAppDispatch, useAppSelector } from "../../redux/hooks/hooks";
import { useRouter } from "next/router";
import Skeleton from "react-loading-skeleton";

const Search: NextPage = () => {
  const router = useRouter();

  const { query } = router.query;

  console.log(query);

  const token = useAppSelector((state) => state.user.jwtToken);

  const [posts, setPosts] = useState<PostInterface[] | null>(null);
  const [isLoadingPosts, setIsLoadingPosts] = useState(true);

  useEffect(() => {
    if (!query) {
      setIsLoadingPosts(false);
      setPosts([]);
      return;
    }

    setIsLoadingPosts(true);

    Axios.post(
      `${process.env.SERVER_HOST}/posts/search`,
      { text: query },
      {
        headers: { Authorization: token || "" },
      }
    )
      .then((response) => {
        console.log(response);
        setIsLoadingPosts(false);
        setPosts(response.data.posts);
      })
      .catch((e) => {
        console.log(e);
        setIsLoadingPosts(false);
      });
  }, [query]);

  const renderPostsCards = (): JSX.Element => {
    if (isLoadingPosts) {
      return (
        <>
          <Skeleton
            style={{ marginBottom: "10px" }}
            borderRadius={13}
            count={10}
            height={150}
          />
        </>
      );
    }

    if (!posts) {
      return (
        <Alert variant="danger">
          <Alert.Heading>Error.</Alert.Heading>
          <p>We are unable to load posts at this time</p>
        </Alert>
      );
    }

    if (posts.length <= 0) {
      return (
        <div className={styles.empty}>
          <img
            className={styles.image}
            src="/illustrations/empty.svg"
            alt="Empty"
          />
          <h1>So empty...</h1>
          <p>
            We could not find any posts that contained &rdquo;{query}&rdquo;
          </p>
        </div>
      );
    }

    return (
      <>
        {posts.map((post: PostInterface, index: number) => {
          return <PostCard key={index} post={post} />;
        })}
      </>
    );
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <h3>Posts for &rdquo;{query}&rdquo;</h3>
        <hr></hr>
        <div className={styles.posts_container}>{renderPostsCards()}</div>
      </main>
    </div>
  );
};

export default Search;
