/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import Axios from "axios";
import Skeleton from "react-loading-skeleton";
import { Alert } from "react-bootstrap";
import PostCard from "../components/posts/postCard/postCard";
import { useAppSelector } from "../redux/hooks/hooks";
import { PostInterface } from "../interfaces/PostInterface";

const Home: NextPage = () => {
  const token = useAppSelector((state) => state.user.jwtToken);

  const [posts, setPosts] = useState<PostInterface[] | null>(null);
  const [isLoadingPosts, setIsLoadingPosts] = useState<boolean>(true);

  useEffect(() => {
    setIsLoadingPosts(true);

    Axios.get(`${process.env.SERVER_HOST}/posts/get_all`, {
      headers: { Authorization: token || "" },
    })
      .then((response) => {
        console.log(response);
        setIsLoadingPosts(false);
        setPosts(response.data.posts);
      })
      .catch((e) => {
        console.log(e);
        setIsLoadingPosts(false);
      });
  }, []);

  const renderPostsCards = (): JSX.Element => {
    if (isLoadingPosts) {
      return (
        <>
          <Skeleton
            style={{ marginBottom: "10px" }}
            borderRadius={13}
            count={10}
            height={150}
          />
        </>
      );
    }

    if (!posts) {
      return (
        <Alert variant="danger">
          <Alert.Heading>Error.</Alert.Heading>
          <p>We are unable to load posts at this time</p>
        </Alert>
      );
    }

    if (posts.length <= 0) {
      return (
        <div className={styles.empty}>
          <img
            className={styles.image}
            src="/illustrations/empty.svg"
            alt="Empty"
          />
          <h1>So empty...</h1>
          <p>Check back later for more posts or post your own one!</p>
        </div>
      );
    }

    return (
      <>
        {posts.map((post: PostInterface, index: number) => {
          return <PostCard key={index} post={post} />;
        })}
      </>
    );
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <h3>Posts</h3>
        <hr></hr>
        <div className={styles.posts_container}>{renderPostsCards()}</div>
      </main>
    </div>
  );
};

export default Home;
